package com.myspace.licusecase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label(value = "Claim No")
	private java.lang.String claimNo;
	@org.kie.api.definition.type.Label(value = "Claim Amount")
	private java.lang.Double claimAmount;

	public CustomerData() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getClaimNo() {
		return this.claimNo;
	}

	public void setClaimNo(java.lang.String claimNo) {
		this.claimNo = claimNo;
	}

	public java.lang.Double getClaimAmount() {
		return this.claimAmount;
	}

	public void setClaimAmount(java.lang.Double claimAmount) {
		this.claimAmount = claimAmount;
	}

	public CustomerData(java.lang.String name, java.lang.Integer age,
			java.lang.String claimNo, java.lang.Double claimAmount) {
		this.name = name;
		this.age = age;
		this.claimNo = claimNo;
		this.claimAmount = claimAmount;
	}

}